Adicionando anos até 2030
pagarme/business-calendar pull request #25
Opened 2021-01-08 18:45 UTC by lucianopf

# Descrição

Esse PR adiciona os calendários até o ano de 2030 baseados em projeções feitas dos feriados da [FEBRABAN](https://feriadosbancarios.febraban.org.br/) e https://www.calendario-365.com.br/feriados/2030.html

Após o merge desse PR na master ainda irei atualizar a branch `gh-pages` com o código e daí deve se tornar disponível para consumo.

2021-01-08 18:58 UTC, matheusvellone submitted a review, later dismissed

2021-01-08 20:06 UTC, czaghi requested changes
As alterações também precisam ser refletidas no diretório data/brazil/

2021-01-08 20:06 UTC, czaghi commented on src/brazil/2028.json
> +			"date": "2028-06-08",
Pelo que vi, esse feriado é em 2028-06-15

2021-01-08 20:06 UTC, czaghi commented on src/brazil/2029.json
> +			"date": "2029-06-08",
Pelo que vi, esse feriado é em 2029-05-31

2021-01-08 20:06 UTC, czaghi commented on src/brazil/2030.json
> +			"date": "2030-06-08",
Pelo que vi, esse feriado é em 2030-06-20

2021-01-09 15:08 UTC, lucianopf commented
@czaghi vc ta certo, obrigado!

Corrigi e gerei novamente os arquivos data, tem como conferir novamente pfv? 🙏

2021-01-11 13:30 UTC, matheusvellone approved these changes

2021-01-11 13:51 UTC, jeanaugustoos approved these changes

2021-01-11 18:13 UTC, czaghi approved these changes

2021-01-12 13:58 UTC, merged